#baseURL = "/"
baseURL = "https://0xZipp0.github.io/theplaybook/"
title = "yusuf aziz mustofa"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[menu]
[[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 1

[Params]
  description = "Just another Note" # Description of your site
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  #twitter_cards = false
  readmore = true # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = false # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = "docs"
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  customCSS = ["background.css"] # Include custom background CSS
  sectionPagesMenu = "main"

[Params.logo]
  title = "playbook" # Logo title, otherwise will use site title
  subtitle = "Just another playbook note" # Logo subtitle

[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility

[Params.sidebar]
  home = "left"   # Configure layout for home page
  list = "left"   # Configure layout for list pages
  single = "left" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "image", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.Information]
  title = "Information"
  image = "/public/aarch.jpeg"

[Params.widgets.social]
  cached = false # activate cache if true
  # Enable parts of social widget
  twitter = "zippo_rhapsody"
  instagram = "7n8.yusufhsn"
  linkedin = "yusufazizmustofa"
  telegram = "r4ph43l"
  github = "0xZipp0"
